FROM python:2.7-slim

RUN apt-get update && \
    apt-get install -y -q python-pip python-dev build-essential nginx curl

RUN pip install -U pip && \
    pip install -U wheel

COPY requirements.txt .
RUN pip wheel \
    --wheel-dir=/var/www/html \
    -r requirements.txt

# forward request and error logs to docker log collector
RUN ln -sf /dev/stdout /var/log/nginx/access.log \
    && ln -sf /dev/stderr /var/log/nginx/error.log

CMD ["nginx", "-g", "daemon off;"]
